services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
      - .env:/usr/app/.env:ro
      - database:/etc/database
    ports:
      - "8080:8080"
volumes:
  database: